---
- name: Download Linux jfrog-cli
  get_url:
    url: "https://releases.jfrog.io/artifactory/jfrog-cli/v1/{{ jfrog_version }}/jfrog-cli-linux-amd64/jfrog"
    dest: '/usr/local/bin/jfrog'
    owner: "{{ jfrog_owner }}"
    group: "{{ jfrog_group }}"
    mode: '0755'
  when: ansible_os_family != "Windows"

- name: Download Windows jfrog-cli
  win_chocolatey:
    name: jfrog-cli
    version: "{{ jfrog_version }}"
    state: present
  when: ansible_os_family == "Windows"
