---
- name: Install Ant (MacOS/Linux)
  include_tasks: linux.yml
  when: ansible_os_family != "Windows"

- name: Install Ant (Windows)
  include_tasks: windows.yml
  when: ansible_os_family == "Windows"
