---
- name: Converge
  hosts: all

  collections:
    - merative.spm_toolbox

  pre_tasks:
    - name: Install JDK
      package:
        name: java-1.8.0-openjdk-devel

  roles:
    - ant

  vars:
    ant_version: "1.10.6"
    ant_base_path: "/opt"
