---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all

  pre_tasks:
    - name: Check if chrome installed
      stat:
        path: "/usr/bin/google-chrome"
      register: chrome_check

    - name: Check if chromedriver installed
      stat: 
        path: "/usr/local/chromedriver"
      register: chromedriver_installed

  tasks:
    - name: Check that chrome exists
      assert:
        that: chrome_check.stat.exists

    - name: Check chromedriver installed 
      assert:
        that: chromedriver_installed.stat.exists
